### ISSUE TITLE
Target types of events in Pux.Html.Events have the wrong type

### ISSUE THREAD

**Issue by dkoontz** [alexmingoia/purescript-pux#40] opened 2016-05-20 17:28 UTC
Currently all events with a target specify `target :: Target` and `type Target = { value :: String }` which is incorrect. Inspecting the value returned in the MouseEvent shows that target is a DOM element. This could be represented by a Pux type or probably better a `DOM.Node.Node` so that it could be passed in directly to DOM functions.

**Comment by alexmingoia** [comment] 2016-05-21 23:25
Great point.

Instead of using `DOM.Node.Node`, I would prefer to parametize `Pux.Html.Events` types (`MouseEvent`, etc.). Instead of `{ target :: { value :: String } }` it would be `type MouseEvent a b = { target :: a, currentTarget :: b }`.

Using it would like look:

``` purescript
module Counter where

import Prelude ((+), (-), const, show)
import Pux.Html (Html, div, span, button, text)
import Pux.Html.Events (MouseEvent, onClick)
import DOM.HTML.Types (HTMLElement)

data Action = Increment (MouseEvent HTMLElement HTMLElement) | Decrement

type State = Int

update :: Action -> State -> State
update (Increment ev) count = count + 1
update Decrement count = count - 1

view :: State -> Html Action
view count =
  div
    []
    [ button [ onClick Increment ] [ text "Increment" ]
    , span [] [ text (show count) ]
    , button [ onClick (const Decrement) ] [ text "Decrement" ]
    ]

```

What does everyone think about that? Other ideas?

**Comment by dkoontz** [comment] 2016-05-22 08:27
Is the parameterization so that you can substitute in any type that you want that matches the structure of the JS object from whatever DOM libraries there might be?

**Comment by alexmingoia** [comment] 2016-05-22 17:58
Yes, exactly.

**Comment by srid** [comment] 2016-11-11 03:51
Give that #80 is a duplicate of this am I correct in understanding that purescript-pux has no way of invoking an `onClick` handler while passing the target element being clicked?

All examples of purescript-pux I have seen so far make use of `const` to purposefully ignore the handler argument. 

I wonder if anyone using purescript-pux for substantial projects have come across this bug, and have found a workaround? In my case I'm writing a board game where it is imperative know _which_ of the cell was clicked ... and I am unable to do this in Pux's `onClick` handler.

**Comment by charleso** [comment] 2016-11-11 04:37
https://github.com/alexmingoia/purescript-pux/pull/81

**Comment by kozak** [comment] 2016-11-11 17:30
@HappyAndHarmless If you don't actually need the dom element, then maybe you could store the cells as a List of tuples `List (CellID, CellState)` and wrap the `Clicked` action of a `Cell` in an `CellClicked CellId CellState` action in the parent component, this way you could have the ID in the action handler without reading it from the DOM (if thats ok). 

If thats the case, have a look at the list of counters examples (https://github.com/debois/elm-parts/blob/master/examples/2-counter-list.elm) or the pair of counters example here: https://github.com/alexmingoia/purescript-pux/blob/master/examples/pair-of-counters/App.purs

**Comment by srid** [comment] 2016-11-12 02:56
@kozak - Ah, yes. That's a better way too.

**Comment by alexmingoia** [comment] 2017-03-30 19:00
The Pux 8 release uses raw DOM events and the event type from purescript-dom. You can do anything you like with the raw DOM events now, and Pux provides a convenience function [`targetValue`](https://pursuit.purescript.org/packages/purescript-pux/8.0.0/docs/Pux.DOM.Events#v:targetValue) for grabbing `.currentTarget.value`.

**Closed as completed** 2017-04-03 06:01 UTC
Labels: bug
