### ISSUE TITLE
Impossible to get the element that was clicked?

### ISSUE THREAD

**Issue by srid** [alexmingoia/purescript-pux#80] opened 2016-11-10 15:17 UTC
I use onClick on a bunch of `div` elements and the Action handler needs to know which of those `div` elements was clicked. 

It does not look like there is a way to do this?

There is `event.target.value` (a String) but the browser craps out when trying to access this field:

```
[Error] TypeError: undefined is not an object (evaluating 'val.constructor')
	(anonymous function) (Anonymous Script 16 (line 20))
	stringify
	stateToString (Anonymous Script 16 (line 19))
	(anonymous function) (Anonymous Script 17 (line 243))
	(anonymous function) (Anonymous Script 18 (line 75))
	(anonymous function) (Anonymous Script 19 (line 25))
	(anonymous function) (Anonymous Script 19 (line 14))
	forEach
	set (Anonymous Script 19 (line 14))
	(anonymous function) (Anonymous Script 19 (line 25))
	(anonymous function) (Anonymous Script 19 (line 14))
	forEach
	set (Anonymous Script 19 (line 14))
	(anonymous function) (Anonymous Script 19 (line 57))
	(anonymous function) (Anonymous Script 19 (line 14))
	forEach
	set (Anonymous Script 19 (line 14))
	(anonymous function) (Anonymous Script 19 (line 14))
	forEach
	set (Anonymous Script 19 (line 14))
	(anonymous function) (Anonymous Script 20 (line 16))
	(anonymous function) (Anonymous Script 21 (line 12))
	(anonymous function)
	dispatchEvent
	invokeGuardedCallback (Anonymous Script 22 (line 70))
	executeDispatch (Anonymous Script 23 (line 89))
	executeDispatchesInOrder (Anonymous Script 23 (line 112))
	executeDispatchesAndRelease (Anonymous Script 24 (line 44))
	forEach
	forEachAccumulated (Anonymous Script 25 (line 25))
	processEventQueue (Anonymous Script 24 (line 231))
	runEventQueueInBatch (Anonymous Script 26 (line 18))
	handleTopLevel (Anonymous Script 26 (line 29))
	handleTopLevelImpl (Anonymous Script 27 (line 73))
	perform (Anonymous Script 9 (line 138))
	batchedUpdates (Anonymous Script 10 (line 63))
	batchedUpdates (Anonymous Script 11 (line 98))
	dispatchEvent (Anonymous Script 27 (line 150))
	dispatchEvent
```

Is this related to #40?

**Comment by charleso** [comment] 2016-11-10 22:08
@HappyAndHarmless Yeah this issue is a duplicate by the looks, the type of `value` needs to change

**Comment by alexmingoia** [comment] 2016-11-10 23:13
Closing as a duplicate of #40

**Closed as completed by alexmingoia** 2016-11-10 23:13 UTC
